
.PHONY: install

install:
	install -m0644 ble-auth.service /usr/lib/systemd/system
	install -m0755 ble-client-launcher.sh /etc/ble-auth
	install -m0644 ble-auth.desktop /usr/share/applications
	install -m0755 ble-auth-config.sh /usr/bin/ble-auth-config
